import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Navbar from "./_components/Navbar";

export const metadata: Metadata = {
  title: "Contact Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="min-h-screen bg-gray-50">
          <Navbar />
          <main className="container mx-auto px-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
